<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController' shared autowired service.

$this->services['PrestaShop\\Module\\LinkList\\Controller\\Admin\\Improve\\Design\\LinkBlockController'] = $instance = new \PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController();

$instance->setContainer($this);

return $instance;
