<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPEc4xYY\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPEc4xYY/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPEc4xYY.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPEc4xYY\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPEc4xYY\appAppKernelProdContainer([
    'container.build_hash' => 'PEc4xYY',
    'container.build_id' => '89e6a6f0',
    'container.build_time' => 1759382536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPEc4xYY');
