-- ========================================
-- YPOK MANAGEMENT SYSTEM - MASTER DATABASE
-- ========================================
-- Database: ypok_management
-- Version: 3.0 COMPLETE
-- Created: 2026
-- Description: Database lengkap untuk sistem manajemen YPOK
-- ========================================
BEGIN;
--
-- Database: ypok_management
--
-- Database creation handled by Supabase
-- ========================================
-- DROP EXISTING TABLES (untuk clean install)
-- ========================================
DROP TABLE IF EXISTS sertifikasi_kohai CASCADE;
DROP TABLE IF EXISTS prestasi_kohai CASCADE;
DROP TABLE IF EXISTS sertifikasi_msh CASCADE;
DROP TABLE IF EXISTS prestasi_msh CASCADE;
DROP TABLE IF EXISTS transaksi_toko CASCADE;
DROP TABLE IF EXISTS produk_variasi CASCADE;
DROP TABLE IF EXISTS kategori_produk CASCADE;
DROP TABLE IF EXISTS produk_toko CASCADE;
DROP TABLE IF EXISTS pembayaran CASCADE;
DROP TABLE IF EXISTS kegiatan CASCADE;
DROP TABLE IF EXISTS pendaftaran_kohai CASCADE;
DROP TABLE IF EXISTS pendaftaran_msh CASCADE;
DROP TABLE IF EXISTS kohai CASCADE;
DROP TABLE IF EXISTS master_sabuk_hitam CASCADE;
DROP TABLE IF EXISTS pengurus CASCADE;
DROP TABLE IF EXISTS legalitas CASCADE;
DROP TABLE IF EXISTS informasi_yayasan CASCADE;
DROP TABLE IF EXISTS dojo CASCADE;
DROP TABLE IF EXISTS provinsi CASCADE;
DROP TABLE IF EXISTS lokasi CASCADE;
DROP TABLE IF EXISTS transaksi CASCADE;
DROP TABLE IF EXISTS users CASCADE;
-- ========================================
-- TABLE: users
-- Untuk autentikasi dan manajemen user
-- ========================================
CREATE TABLE users (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(50) NOT NULL,
  password varchar(255) NOT NULL,
  nama_lengkap varchar(100) NOT NULL,
  email varchar(100) DEFAULT NULL,
  role varchar(50) DEFAULT 'user',
  foto_profil varchar(255) DEFAULT NULL,
  status varchar(50) DEFAULT 'active',
  last_login timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT users_username_key UNIQUE (username)
);
-- ========================================
-- TABLE: provinsi
-- Untuk data provinsi/wilayah
-- ========================================
CREATE TABLE IF NOT EXISTS provinsi (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nama_provinsi varchar(100) NOT NULL,
  kode_provinsi varchar(10) DEFAULT NULL,
  logo varchar(255) DEFAULT NULL,
  total_dojo integer DEFAULT 0,
  total_anggota integer DEFAULT 0,
  anggota_aktif integer DEFAULT 0,
  anggota_non_aktif integer DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: dojo
-- Untuk data dojo/cabang per provinsi
-- ========================================
CREATE TABLE IF NOT EXISTS dojo (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  provinsi_id integer NOT NULL,
  nama_dojo varchar(100) NOT NULL,
  alamat text DEFAULT NULL,
  total_anggota integer DEFAULT 0,
  anggota_aktif integer DEFAULT 0,
  anggota_non_aktif integer DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_dojo_provinsi FOREIGN KEY (provinsi_id) REFERENCES provinsi (id) ON DELETE CASCADE
);
-- ========================================
-- TABLE: lokasi
-- Untuk data lokasi kegiatan
-- ========================================
CREATE TABLE lokasi (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nama_lokasi varchar(100) NOT NULL,
  alamat text DEFAULT NULL,
  koordinat varchar(100) DEFAULT NULL,
  kota varchar(50) DEFAULT NULL,
  provinsi varchar(50) DEFAULT NULL,
  kapasitas integer DEFAULT NULL,
  fasilitas text DEFAULT NULL,
  status varchar(50) DEFAULT 'aktif',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: informasi_yayasan
-- Untuk data identitas yayasan
-- ========================================
CREATE TABLE IF NOT EXISTS informasi_yayasan (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nama_lengkap varchar(255) NOT NULL,
  nama_singkat varchar(100) DEFAULT NULL,
  tanggal_berdiri date DEFAULT NULL,
  status_hukum varchar(100) DEFAULT NULL,
  alamat text DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  telepon varchar(50) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  visi text DEFAULT NULL,
  misi text DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: pengurus
-- Untuk data pengurus yayasan
-- ========================================
CREATE TABLE IF NOT EXISTS pengurus (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nik varchar(50) DEFAULT NULL,
  nama varchar(255) NOT NULL,
  tempat_lahir varchar(100) DEFAULT NULL,
  tanggal_lahir date DEFAULT NULL,
  jabatan varchar(100) NOT NULL,
  periode varchar(50) DEFAULT NULL,
  tanggal_sk date DEFAULT NULL,
  no_sk varchar(100) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  telepon varchar(50) DEFAULT NULL,
  alamat text DEFAULT NULL,
  pendidikan_terakhir varchar(100) DEFAULT NULL,
  foto varchar(255) DEFAULT NULL,
  foto_url text DEFAULT NULL,
  status varchar(50) DEFAULT 'Aktif',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: legalitas
-- Untuk dokumen legal yayasan
-- ========================================
CREATE TABLE IF NOT EXISTS legalitas (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  jenis_dokumen varchar(100) NOT NULL,
  nomor_dokumen varchar(100) NOT NULL,
  tanggal_terbit date NOT NULL,
  tanggal_kadaluarsa date DEFAULT NULL,
  instansi_penerbit varchar(100) NOT NULL,
  file_dokumen varchar(255) DEFAULT NULL,
  status varchar(50) DEFAULT 'Aktif',
  keterangan text DEFAULT NULL,
  is_permanent boolean DEFAULT false,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: master_sabuk_hitam (MSH)
-- Untuk data Master Sabuk Hitam (Dan 1-9)
-- ========================================
CREATE TABLE master_sabuk_hitam (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  no_msh varchar(50) DEFAULT NULL,
  nama varchar(255) NOT NULL,
  tempat_lahir varchar(100) DEFAULT NULL,
  tanggal_lahir date DEFAULT NULL,
  jenis_kelamin varchar(50) DEFAULT 'L',
  tingkat_dan varchar(50) DEFAULT NULL,
  tanggal_lulus date DEFAULT NULL,
  nomor_ijazah varchar(100) DEFAULT NULL,
  foto varchar(255) DEFAULT NULL,
  alamat text DEFAULT NULL,
  no_telp varchar(20) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  dojo_cabang varchar(100) DEFAULT NULL,
  status varchar(50) DEFAULT 'Aktif',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));
-- ========================================
-- TABLE: prestasi_msh
-- Untuk prestasi Master Sabuk Hitam
-- ========================================
CREATE TABLE prestasi_msh (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  msh_id integer NOT NULL,
  nama_prestasi varchar(255) NOT NULL,
  tanggal_prestasi date DEFAULT NULL,
  keterangan text DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT prestasi_msh_ibfk_1 FOREIGN KEY (msh_id) REFERENCES master_sabuk_hitam (id) ON DELETE CASCADE ON UPDATE CASCADE
);
-- ========================================
-- TABLE: sertifikasi_msh
-- Untuk sertifikasi MSH
-- ========================================
CREATE TABLE sertifikasi_msh (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  msh_id integer NOT NULL,
  nama_sertifikasi varchar(255) DEFAULT NULL,
  nomor_sertifikat varchar(100) DEFAULT NULL,
  penerbit varchar(100) DEFAULT NULL,
  level varchar(50) DEFAULT NULL,
  tanggal_terbit date DEFAULT NULL,
  tanggal_kadaluarsa date DEFAULT NULL,
  status varchar(50) DEFAULT 'valid',
  file_sertifikat varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT sertifikasi_msh_ibfk_1 FOREIGN KEY (msh_id) REFERENCES master_sabuk_hitam (id) ON DELETE CASCADE ON UPDATE CASCADE
);
-- ========================================
-- TABLE: kohai
-- Untuk data siswa/kohai (Kyu 1-10)
-- ========================================
CREATE TABLE kohai (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  kode_kohai varchar(50) NOT NULL,
  nama varchar(255) NOT NULL,
  tempat_lahir varchar(100) DEFAULT NULL,
  tanggal_lahir date DEFAULT NULL,
  jenis_kelamin varchar(50) DEFAULT 'L',
  tingkat_kyu varchar(50) DEFAULT NULL,
  sabuk varchar(50) DEFAULT NULL,
  dojo_cabang varchar(100) DEFAULT NULL,
  no_telp varchar(20) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  status varchar(50) DEFAULT 'Aktif',
  alamat text DEFAULT NULL,
  foto varchar(255) DEFAULT NULL,
  nama_wali varchar(255) DEFAULT NULL,
  no_telp_wali varchar(20) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT kohai_kode_kohai_key UNIQUE (kode_kohai));
-- ========================================
-- TABLE: prestasi_kohai
-- Untuk prestasi siswa/kohai
-- ========================================
CREATE TABLE prestasi_kohai (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  kohai_id integer NOT NULL,
  nama_prestasi varchar(255) NOT NULL,
  tanggal_prestasi date DEFAULT NULL,
  keterangan text DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT prestasi_kohai_ibfk_1 FOREIGN KEY (kohai_id) REFERENCES kohai (id) ON DELETE CASCADE ON UPDATE CASCADE
);
-- ========================================
-- TABLE: sertifikasi_kohai
-- Untuk sertifikasi ujian kenaikan sabuk
-- ========================================
CREATE TABLE sertifikasi_kohai (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  kohai_id integer NOT NULL,
  nama_sertifikasi varchar(255) DEFAULT NULL,
  nomor_sertifikat varchar(100) DEFAULT NULL,
  penerbit varchar(100) DEFAULT NULL,
  tanggal_terbit date DEFAULT NULL,
  tanggal_kadaluarsa date DEFAULT NULL,
  status varchar(50) DEFAULT 'valid',
  file_sertifikat varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT sertifikasi_kohai_ibfk_1 FOREIGN KEY (kohai_id) REFERENCES kohai (id) ON DELETE CASCADE ON UPDATE CASCADE
);
-- ========================================
-- TABLE: pendaftaran_msh
-- Untuk pendaftaran MSH baru
-- ========================================
CREATE TABLE IF NOT EXISTS pendaftaran_msh (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  no_msh varchar(20) NOT NULL,
  nama_lengkap varchar(100) NOT NULL,
  foto_msh varchar(255) DEFAULT NULL,
  tempat_lahir varchar(50) NOT NULL,
  tanggal_lahir date NOT NULL,
  jenis_kelamin varchar(50) NOT NULL,
  tingkat_dan varchar(20) NOT NULL,
  dojo_cabang varchar(50) NOT NULL,
  no_telp varchar(15) NOT NULL,
  email varchar(100) DEFAULT NULL,
  alamat text NOT NULL,
  status varchar(50) DEFAULT 'Pending',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: pendaftaran_kohai
-- Untuk pendaftaran kohai baru
-- ========================================
CREATE TABLE IF NOT EXISTS pendaftaran_kohai (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  no_kohai varchar(20) NOT NULL,
  nama_lengkap varchar(100) NOT NULL,
  foto_kohai varchar(255) DEFAULT NULL,
  tempat_lahir varchar(50) NOT NULL,
  tanggal_lahir date NOT NULL,
  jenis_kelamin varchar(50) NOT NULL,
  no_telp varchar(15) NOT NULL,
  email varchar(100) DEFAULT NULL,
  alamat text NOT NULL,
  nama_wali varchar(100) NOT NULL,
  no_telp_wali varchar(15) NOT NULL,
  status varchar(50) DEFAULT 'Pending',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: pembayaran
-- Untuk transaksi pembayaran
-- ========================================
CREATE TABLE IF NOT EXISTS pembayaran (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nama_kohai varchar(255) NOT NULL,
  kategori varchar(100) NOT NULL,
  jumlah decimal(15,2) NOT NULL,
  tanggal_bayar date NOT NULL,
  metode_pembayaran varchar(50) DEFAULT NULL,
  bukti_pembayaran varchar(255) DEFAULT NULL,
  status varchar(50) DEFAULT 'Pending',
  keterangan text DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));
-- ========================================
-- TABLE: transaksi
-- Untuk laporan keuangan yayasan
-- ========================================
CREATE TABLE IF NOT EXISTS transaksi (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tanggal date NOT NULL,
  jenis varchar(50) NOT NULL,
  kategori varchar(100) DEFAULT NULL,
  keterangan text NOT NULL,
  jumlah decimal(15,2) NOT NULL,
  saldo decimal(15,2) DEFAULT 0.00,
  created_by integer DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_transaksi_user FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);
-- ========================================
-- TABLE: kegiatan
-- Untuk data kegiatan/event
-- ========================================
CREATE TABLE IF NOT EXISTS kegiatan (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nama_kegiatan varchar(255) NOT NULL,
  jenis_kegiatan varchar(100) DEFAULT NULL,
  tanggal_kegiatan date NOT NULL,
  waktu_mulai time DEFAULT NULL,
  waktu_selesai time DEFAULT NULL,
  lokasi_id integer DEFAULT NULL,
  lokasi_nama varchar(255) DEFAULT NULL,
  peserta_msh text DEFAULT NULL,
  peserta_kohai text DEFAULT NULL,
  biaya decimal(15,2) DEFAULT 0,
  dokumentasi text DEFAULT NULL,
  keterangan text DEFAULT NULL,
  tampil_di_berita boolean DEFAULT FALSE,
  foto varchar(255) DEFAULT NULL,
  status varchar(50) DEFAULT 'Akan Datang',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_kegiatan_lokasi FOREIGN KEY (lokasi_id) REFERENCES lokasi (id) ON DELETE SET NULL
);
-- ========================================
-- TABLE: kategori_produk
-- Untuk kategori produk toko
-- ========================================
CREATE TABLE IF NOT EXISTS kategori_produk (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nama_kategori varchar(100) NOT NULL UNIQUE,
  deskripsi text DEFAULT NULL,
  icon varchar(50) DEFAULT '📦',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
-- ========================================
-- TABLE: produk_toko
-- Untuk produk toko
-- ========================================
CREATE TABLE IF NOT EXISTS produk_toko (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  kode_produk varchar(50) NOT NULL,
  nama_produk varchar(255) NOT NULL,
  kategori varchar(100) DEFAULT NULL,
  harga decimal(15,2) NOT NULL,
  stok integer NOT NULL DEFAULT 0,
  has_variasi boolean DEFAULT false,
  status varchar(50) DEFAULT 'Tersedia',
  deskripsi text DEFAULT NULL,
  spesifikasi text DEFAULT NULL,
  gambar varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT produk_toko_kode_produk_key UNIQUE (kode_produk)
);
-- ========================================
-- TABLE: produk_variasi
-- Untuk variasi produk (ukuran, warna, dll)
-- ========================================
CREATE TABLE IF NOT EXISTS produk_variasi (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  produk_id integer NOT NULL,
  atribut_1 varchar(100) DEFAULT NULL,
  nilai_1 varchar(100) DEFAULT NULL,
  atribut_2 varchar(100) DEFAULT NULL,
  nilai_2 varchar(100) DEFAULT NULL,
  stok integer NOT NULL DEFAULT 0,
  harga_tambahan decimal(15,2) DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_produk_variasi FOREIGN KEY (produk_id) REFERENCES produk_toko (id) ON DELETE CASCADE
);
-- ========================================
-- TABLE: transaksi_toko
-- Untuk transaksi penjualan produk
-- ========================================
CREATE TABLE IF NOT EXISTS transaksi_toko (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_transaksi varchar(50) NOT NULL,
  produk_id integer NOT NULL,
  pembeli varchar(255) NOT NULL,
  lokasi varchar(255) NOT NULL,
  alamat text DEFAULT NULL,
  jumlah integer NOT NULL,
  total_harga decimal(15,2) NOT NULL,
  metode_pembayaran varchar(50) NOT NULL,
  tanggal timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  catatan text DEFAULT NULL,
  variasi_info varchar(255) DEFAULT NULL,
  created_by integer DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT transaksi_toko_id_transaksi_key UNIQUE (id_transaksi),
  CONSTRAINT fk_transaksi_produk FOREIGN KEY (produk_id) REFERENCES produk_toko (id) ON DELETE CASCADE
);
-- ========================================n-- INSERT DEFAULT DATAn-- ========================================
-- Default Admin User
INSERT INTO users (username, password, nama_lengkap, email, role, status) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Administrator YPOK', 'admin@ypok.com', 'admin', 'active');
-- Default Kategori Produk
INSERT INTO kategori_produk (nama_kategori, deskripsi, icon) VALUES
('Seragam (Karate Gi)', 'Pakaian latihan karate resmi', '🥋'),
('Pelindung', 'Alat pelindung tubuh untuk latihan', '🛡️'),
('Senjata Latihan', 'Peralatan senjata untuk latihan kata', '⚔️'),
('Sabuk', 'Sabuk tingkat karate', '🥋'),
('Merchandise', 'Produk merchandise YPOK', '🎁'),
('Aksesoris', 'Aksesoris pendukung latihan', '👕'),
('Perlengkapan', 'Perlengkapan latihan lainnya', '🎒');
-- Sample Transaksi Keuangan
INSERT INTO transaksi (tanggal, jenis, kategori, keterangan, jumlah, saldo, created_by) VALUES
('2024-01-01', 'pemasukan', 'Donasi', 'Donasi dari Alumni', 5000000.00, 5000000.00, 1),
('2024-01-05', 'pengeluaran', 'Operasional', 'Pembelian ATK', 500000.00, 4500000.00, 1),
('2024-01-10', 'pemasukan', 'Infaq', 'Infaq Jumat', 1000000.00, 5500000.00, 1),
('2024-01-15', 'pengeluaran', 'Konsumsi', 'Konsumsi Rapat', 300000.00, 5200000.00, 1);
COMMIT;
-- ========================================
-- DATABASE UPDATES & MODIFICATIONS
-- ========================================
-- Bagian ini berisi update struktur tabel untuk fitur terbaru
-- ========================================
-- ========================================
-- UPDATE 1: Tabel Master Sabuk Hitam (MSH)
-- Tanggal: 2026-03-04
-- ========================================
-- Tambahkan field tanggal_ujian dan jenis_keanggotaan
ALTER TABLE master_sabuk_hitam 
ADD COLUMN tanggal_ujian DATE NULL,
ADD COLUMN jenis_keanggotaan VARCHAR(50) DEFAULT 'Reguler';
-- Update data existing dengan default value
UPDATE master_sabuk_hitam 
SET jenis_keanggotaan = 'Reguler' 
WHERE jenis_keanggotaan IS NULL;
-- Komentar untuk field
-- ========================================
-- UPDATE 2: Tabel Kohai
-- Tanggal: 2026-03-04
-- ========================================
-- Tambahkan field baru yang diperlukan
ALTER TABLE kohai 
ADD COLUMN no_registrasi_ijazah VARCHAR(255) NULL,
ADD COLUMN tanggal_ujian DATE NULL,
ADD COLUMN asal_sekolah VARCHAR(255) NULL,
ADD COLUMN asal_provinsi VARCHAR(255) NULL,
ADD COLUMN keterangan TEXT NULL;
-- Update data existing dengan default value jika diperlukan
UPDATE kohai 
SET asal_provinsi = dojo_cabang 
WHERE asal_provinsi IS NULL AND dojo_cabang IS NOT NULL;
-- Komentar untuk field
-- ========================================
-- UPDATE 3: Tabel Pembayaran
-- Tanggal: 2026-02-12
-- ========================================
-- Tambah kolom nama_kohai sebagai pengganti kohai_id (untuk input nama universal)
ALTER TABLE pembayaran
ADD COLUMN IF NOT EXISTS total_tagihan DECIMAL(15,2) DEFAULT NULL;
ALTER TABLE pembayaran
ADD COLUMN IF NOT EXISTS nominal_dibayar DECIMAL(15,2) DEFAULT NULL;
ALTER TABLE pembayaran
ADD COLUMN IF NOT EXISTS sisa DECIMAL(15,2) DEFAULT NULL;

-- ========================================
-- POSTGRESQL FUNCTIONS & TRIGGERS
-- ========================================
CREATE OR REPLACE FUNCTION update_provinsi_stats(p_provinsi_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE provinsi
    SET
        total_dojo = (SELECT COUNT(*) FROM dojo WHERE provinsi_id = p_provinsi_id),
        total_anggota = (SELECT COALESCE(SUM(total_anggota), 0) FROM dojo WHERE provinsi_id = p_provinsi_id),
        anggota_aktif = (SELECT COALESCE(SUM(anggota_aktif), 0) FROM dojo WHERE provinsi_id = p_provinsi_id),
        anggota_non_aktif = (SELECT COALESCE(SUM(anggota_non_aktif), 0) FROM dojo WHERE provinsi_id = p_provinsi_id)
    WHERE id = p_provinsi_id;
END;
$$;

CREATE OR REPLACE FUNCTION trg_dojo_after_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM update_provinsi_stats(NEW.provinsi_id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_dojo_after_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.provinsi_id IS DISTINCT FROM NEW.provinsi_id THEN
        PERFORM update_provinsi_stats(OLD.provinsi_id);
    END IF;
    PERFORM update_provinsi_stats(NEW.provinsi_id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_dojo_after_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM update_provinsi_stats(OLD.provinsi_id);
    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS after_dojo_insert ON dojo;
CREATE TRIGGER after_dojo_insert AFTER INSERT ON dojo FOR EACH ROW EXECUTE FUNCTION trg_dojo_after_insert();

DROP TRIGGER IF EXISTS after_dojo_update ON dojo;
CREATE TRIGGER after_dojo_update AFTER UPDATE ON dojo FOR EACH ROW EXECUTE FUNCTION trg_dojo_after_update();

DROP TRIGGER IF EXISTS after_dojo_delete ON dojo;
CREATE TRIGGER after_dojo_delete AFTER DELETE ON dojo FOR EACH ROW EXECUTE FUNCTION trg_dojo_after_delete();

